services:
  paymentdb:
    container_name: paymentdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=PaymentDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_paymentdb:/var/lib/postgresql/data